### ISSUE TITLE
Build fails with Go 1.23

### ISSUE THREAD

**Issue by stefanb** [tickstep/aliyunpan#437]
See:
* Attempt to build with Go 1.23: https://github.com/Homebrew/homebrew-core/pull/175310
* Upstream issue: https://github.com/tickstep/library-go/issues/1

**Comment by tickstep** [comment]
fix it in the latest version

**Comment by stefanb** [comment]
Build with Go 1.23 still fails, please see 
* https://github.com/Homebrew/homebrew-core/pull/181082:

```
# github.com/tickstep/library-go/cachepool
/home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/tickstep/library- go@v0.1.2/cachepool/cachepool.go:52:11: undefined: RawMallocByteSlice
/home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/tickstep/library-go@v0.1.2/cachepool/idcachepool.go:49:11: undefined: RawMallocByteSlice
/home/linuxbrew/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/tickstep/library-go@v0.1.2/cachepool/syncpool.go:15:11: undefined: RawMallocByteSlice
```
